global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  # Cluster Linux: server1, server2, server3 (via túneles SSH 9101-9103)
  - job_name: node_exporter_linux
    static_configs:
      - targets: ['localhost:9101']
        labels:
          node: server1
          nodename: server1
          cluster: linux
      - targets: ['localhost:9102']
        labels:
          node: server2
          nodename: server2
          cluster: linux
      - targets: ['localhost:9103']
        labels:
          node: server3
          nodename: server3
          cluster: linux

  # Cluster OpenStack: worker1, worker2, worker3 (via túneles SSH 9122-9124)
  - job_name: node_exporter_openstack
    static_configs:
      - targets: ['localhost:9122']
        labels:
          node: worker1
          nodename: worker1
          cluster: openstack
      - targets: ['localhost:9123']
        labels:
          node: worker2
          nodename: worker2
          cluster: openstack
      - targets: ['localhost:9124']
        labels:
          node: worker3
          nodename: worker3
          cluster: openstack